// utils/orderStatus.js

/**
 * Centrally defined Order Lifecycle Statuses for Jack Essentials
 */
const ORDER_STATUS = {
  PENDING_PAYMENT: 'Pending Payment',
  PENDING_REVIEW: 'Pending Review',
  PENDING: 'Pending',
  PAID: 'Paid',
  PROCESSING: 'Processing',
  PACKED: 'Packed',
  SHIPPED: 'Shipped',
  OUT_FOR_DELIVERY: 'OutForDelivery',
  DELIVERED: 'Delivered',
  CANCELLED: 'Cancelled',
  RETURN_REQUESTED: 'ReturnRequested',
  RETURN_APPROVED: 'ReturnApproved',
  RETURNED: 'Returned',
  RTO: 'RTO',
  REFUNDED: 'Refunded'
};

/**
 * Allowed state transitions mapping for strict state machine enforcement
 */
const ALLOWED_STATE_TRANSITIONS = {
  [ORDER_STATUS.PENDING_PAYMENT]: [ORDER_STATUS.PAID, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PENDING_REVIEW]: [ORDER_STATUS.PENDING, ORDER_STATUS.PAID, ORDER_STATUS.PROCESSING, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PENDING]: [ORDER_STATUS.PAID, ORDER_STATUS.PROCESSING, ORDER_STATUS.PACKED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PAID]: [ORDER_STATUS.PROCESSING, ORDER_STATUS.PACKED, ORDER_STATUS.SHIPPED, ORDER_STATUS.REFUNDED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PROCESSING]: [ORDER_STATUS.PACKED, ORDER_STATUS.SHIPPED, ORDER_STATUS.CANCELLED, ORDER_STATUS.REFUNDED],
  [ORDER_STATUS.PACKED]: [ORDER_STATUS.SHIPPED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.SHIPPED]: [ORDER_STATUS.OUT_FOR_DELIVERY, ORDER_STATUS.DELIVERED, ORDER_STATUS.RTO, ORDER_STATUS.REFUNDED],
  [ORDER_STATUS.OUT_FOR_DELIVERY]: [ORDER_STATUS.DELIVERED, ORDER_STATUS.RTO],
  [ORDER_STATUS.DELIVERED]: [ORDER_STATUS.RETURN_REQUESTED, ORDER_STATUS.RETURNED, ORDER_STATUS.REFUNDED],
  [ORDER_STATUS.RETURN_REQUESTED]: [ORDER_STATUS.RETURN_APPROVED, ORDER_STATUS.RETURNED, ORDER_STATUS.CANCELLED, ORDER_STATUS.DELIVERED],
  [ORDER_STATUS.RETURN_APPROVED]: [ORDER_STATUS.RETURNED, ORDER_STATUS.REFUNDED],
  [ORDER_STATUS.RETURNED]: [ORDER_STATUS.REFUNDED],
  [ORDER_STATUS.RTO]: [ORDER_STATUS.REFUNDED, ORDER_STATUS.RETURNED],
  [ORDER_STATUS.CANCELLED]: [ORDER_STATUS.REFUNDED],
  [ORDER_STATUS.REFUNDED]: []
};

/**
 * Validate if a state transition is permissible
 * @param {string} currentState 
 * @param {string} nextState 
 * @returns {boolean}
 */
const isValidTransition = (currentState, nextState) => {
  const allowed = ALLOWED_STATE_TRANSITIONS[currentState] || [];
  return allowed.includes(nextState);
};

module.exports = {
  ORDER_STATUS,
  ALLOWED_STATE_TRANSITIONS,
  isValidTransition
};